const keyNameMap = {
  Backspace: 'Backspace',
  Tab: 'Tab',
  Enter: 'Enter',
  CapsLock: 'CapsLock',
  Escape: 'Esc',
  Space: '',
  PageUp: 'PgUp',
  PageDown: 'PgDn',
  End: 'End',
  Home: 'Home',
  ArrowLeft: '⬅',
  ArrowUp: '⬆',
  ArrowRight: '→',
  ArrowDown: '⬇',
  Insert: 'Ins',
  Delete: 'Del',
  '0': '0',
  '1': '1',
  '2': '2',
  '3': '3',
  '4': '4',
  '5': '5',
  '6': '6',
  '7': '7',
  '8': '8',
  '9': '9',
  A: 'A',
  B: 'B',
  C: 'C',
  D: 'D',
  E: 'E',
  F: 'F',
  G: 'G',
  H: 'H',
  I: 'I',
  J: 'J',
  K: 'K',
  L: 'L',
  M: 'M',
  N: 'N',
  O: 'O',
  P: 'P',
  Q: 'Q',
  R: 'R',
  S: 'S',
  T: 'T',
  U: 'U',
  V: 'V',
  W: 'W',
  X: 'X',
  Y: 'Y',
  Z: 'Z',
  Numpad0: 0,
  Numpad1: 1,
  Numpad2: 2,
  Numpad3: 3,
  Numpad4: 4,
  Numpad5: 5,
  Numpad6: 6,
  Numpad7: 7,
  Numpad8: 8,
  Numpad9: 9,
  NumpadMultiply: '*',
  NumpadAdd: '+',
  NumpadSubtract: '-',
  NumpadDecimal: '.',
  NumpadDivide: '/',
  F1: 'F1',
  F2: 'F2',
  F3: 'F3',
  F4: 'F4',
  F5: 'F5',
  F6: 'F6',
  F7: 'F7',
  F8: 'F8',
  F9: 'F9',
  F10: 'F10',
  F11: 'F11',
  F12: 'F12',
  Semicolon: '; :',
  Equal: '= +',
  Comma: ', <',
  Minus: '- _',
  Period: '. >',
  Slash: '/ ?',
  Backquote: '` ~',
  BracketLeft: '[ {',
  Backslash: '\\ |',
  BracketRight: '] }',
  Quote: '\' "',
  Ctrl: 'Ctrl',
  CtrlRight: 'Ctrl',
  Alt: 'Alt',
  AltRight: 'Alt',
  Shift: 'Shift',
  ShiftRight: 'Shift',
  Meta: 'Win',
  MetaRight: 'Win',
  NumLock: 'NumLk',
  ScrollLock: 'ScrLk',
  PrintScreen: 'PrtSc',
  Pause: 'Pause',
};

export default keyNameMap;
